FROM python:3.9.19-slim
LABEL maintainer="Sypchik"

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip && \
    pip install python-dotenv && \
    pip install -r ./requirements.txt

CMD ["python", "main.py"]

